website/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

class User(UserMixin):
    def __init__(self, username, password):
        self.id = 1  # Since we have only one user, set a static user ID
        self.username = username
        self.password = generate_password_hash(password)  # Hash the password during user creation

    @staticmethod
    def get(user_id):
        if user_id == 1:
            return User('admin', '1234')  # Return the user object for the static user ID
        return None  # Return None for other user IDs (not used in this example)

    def check_password(self, password):
        return check_password_hash(self.password, password)

website/__init__.py
#Identify file "websites" as a python package

from flask import Flask
from os import path
from flask_login import LoginManager

def create_app():
    app = Flask(__name__)  #Create a Flask application instance
    app.secret_key = "abc" #Set a secret key for the application

    #Import and register the 'views' and 'auth' blueprints
    from .views import views
    from .man import man
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    app.register_blueprint(man, url_prefix='/')

    #Import the Use model
    from .models import User
    
    #Initialize the LoginManager
    login_manager = LoginManager()
    #Set the login view for the LoginManager
    login_manager.login_view = 'auth.login'
    # Initialize the LoginManager with the Flask app
    login_manager.init_app(app)

    # Define a user loader function for the LoginManager
    @login_manager.user_loader
    def load_user(id):
        return User.get(int(id))

    # Return the Flask app instance
    return app

website/auth.py
#Flask blueprint handling user authentication and lgin functionality

from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__) #labelling this blueprint as 'auth' 

#Login route
@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST': #condition when 'submit' button is pressed
        username = request.form.get('username') #storing input username data
        password = request.form.get('password') #storing input password
        user = User.get(1)  # Get static user object with ID 1 from 'model.py' (username and password)

        if username == '' or password == '': #condition when either username or password is null or both
            flash("Null entry detected.", category='error') #pop up an error message
        elif not user or not user.check_password(password): #condition when either username or password or both do not match
            flash("Incorrect username or password, try again.", category='error') #pop up an error message
        else: #condition when both username and password matched
            flash("Logged in successfully!", category='success') #pop up a success message
            login_user(user, remember=True) #remember has logged in (only logged out automatically when page is restarted)
            return redirect(url_for('views.home')) #go to homepage

    return render_template("login.html", user=current_user) #when submit button on login page is not pressed, stay on login page

#Manual route
@auth.route('/manual') 
@login_required #this function is only accessible after successful login
def manual():
    return render_template("manual.html", user=current_user) #go to manual page

#Logout route
@auth.route('/logout')
@login_required #this function is only accessible after successful login
def logout():
    logout_user() #remember user has logged out
    flash("Logged out successfully!", category='success')
    return redirect(url_for('auth.login')) #go to login page

website/views.py
#Home page blueprint

import cv2
from flask import Blueprint, render_template, Response
from flask_login import login_required, current_user

views = Blueprint('views', __name__)

# Function to capture video frames
def capture_frames():
    camera = cv2.VideoCapture(0)  # Use the appropriate camera index if multiple cameras are available
    camera.set(cv2.CAP_PROP_FRAME_WIDTH, 640) #640
    camera.set(cv2.CAP_PROP_FRAME_HEIGHT, 480) #480

    while True:
        success, frame = camera.read()
        if not success:
            break

        # Encode the frame as JPEG
        ret, buffer = cv2.imencode('.jpg', frame)
        if not ret:
            break

        # Yield the resulting image frame
        yield b'--frame\r\n' b'Content-Type: image/jpeg\r\n\r\n' + buffer.tobytes() + b'\r\n'

    # Release the camera
    camera.release()

@views.route('/')
@login_required
def home():
    return render_template("home.html")

@views.route('/video_feed')
@login_required
def video_feed():
    return Response(capture_frames(), mimetype='multipart/x-mixed-replace; boundary=frame')

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <title>{% block title %}Home{% endblock %}</title>
  </head>

  <body>
    {% if request.path != '/login' %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          <a class="nav-item nav-link" id="auto" href="/">Auto</a>
          <a class="nav-item nav-link" id="man" href="/manual">Manual</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% endif %}
        </div>
      </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %} 
      {% if messages %} 
        {% for category, message in messages %} 
          {% if category =='error' %}
            <div class="alert alert-danger alter-dismissable fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>

          {% else %}
            <div class="alert alert-success alter-dismissable fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endif %}
        {% endfor %} 
      {% endif %} 
    {% endwith %}

    <div class="container">
    {% block content %}
    {% endblock %}
    </div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

  </body>
</html>

website/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
  <h3>This is the homepage</h3>
  <img src="{{ url_for('views.video_feed') }}" alt="Camera Feed" width="560" height="400" />
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}LogIn{% endblock %}

{% block content%}
<form method="POST">
    <center>
      <img src="https://img.freepik.com/premium-vector/green-leaf-vector-icon-isolated-recycle-ecology-icon-natural-leaf-icon-eco-nature-healthy-concept-eps-10_158224-115.jpg?w=2000"width="150" height="150">
    </center>
    <h2 align="center">Agrovate</h2>
    <h5 align="center" style = "font-family:verdana,sans-serif;font-size:16px;font-style:italic;">
      Innovative solution for modern agriculture
    </h5>
    <div class="form-group">
      <label for="username">Username:</label>
      <input
        type="username"
        class="form-control"
        id="username"
        name="username"
        placeholder="Enter username"
      />
    </div>
    <div class="form-group">
      <label for="password">Password:</label>
      <input
        type="password"
        class="form-control"
        id="password"
        name="password"
        placeholder="Enter password"
      />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Login</button>
  </form>
  {% endblock %}

website/templates/manual.html
{% extends "base.html" %}

{% block title %}Manual{% endblock %}

{% block content %}
<style>
  .container {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
  }

  .button-row {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    margin-bottom: 10px;
  }

  .button1,
  .button2 {
    display: inline-block;
    padding: 15px 25px;
    font-size: 24px;
    cursor: pointer;
    text-align: center;
    text-decoration: none;
    outline: none;
    color: #fff;
    border: none;
    border-radius: 15px;
    box-shadow: 0 9px #999;
    margin: 10px;
  }

  .button1 {
    background-color: #4CAF50;
  }

  .button1:hover {
    background-color: #3e8e41;
  }

  .button1:active {
    background-color: #3e8e41;
    box-shadow: 0 5px #666;
    transform: translateY(4px);
  }

  .button2 {
    background-color: #af514c;
  }

  .button2:hover {
    background-color: #763632;
  }

  .button2:active {
    background-color: #763632;
    box-shadow: 0 5px #666;
    transform: translateY(4px);
  }
</style>

<div class="container">
  <div class="button-row">
    <button class="button1" id="motorXCW" onmousedown="Button_ON(1)" onmouseup="Button_OFF(2)">X CW</button>
    <button class="button1" id="motorYCW" onmousedown="Button_ON(5)" onmouseup="Button_OFF(6)">Y CW</button>
    <button class="button1" id="motorZCW" onmousedown="Button_ON(9)" onmouseup="Button_OFF(10)">Z CW</button>
  </div>
  <div class="button-row">
    <button class="button2" id="motorXCCW" onmousedown="Button_ON(3)" onmouseup="Button_OFF(4)">X CCW</button>
    <button class="button2" id="motorYCCW" onmousedown="Button_ON(7)" onmouseup="Button_OFF(8)">Y CCW</button>
    <button class="button2" id="motorZCCW" onmousedown="Button_ON(11)" onmouseup="Button_OFF(12)">Z CCW</button>
  </div>
</div>

<script>
  function Button_ON(move) {
    var button = '';

    if (move == 1) {
      button = 'XCW/on';
    } else if (move == 3) {
      button = 'XCCW/on';
    } else if (move == 5) {
      button = 'YCW/on';
    } else if (move == 7) {
      button = 'YCCW/on';
    } else if (move == 9) {
      button = 'ZCW/on';
    } else if (move == 11) {
      button = 'ZCCW/on';
    }

    var xhr = new XMLHttpRequest();
    xhr.open('get', '' + button);
    xhr.send();
  }

  function Button_OFF(move) {
    var button = '';

    if (move == 2) {
      button = 'XCW/off';
    } else if (move == 4) {
      button = 'XCCW/off';
    } else if (move == 6) {
      button = 'YCW/off';
    } else if (move == 8) {
      button = 'YCCW/off';
    } else if (move == 10) {
      button = 'ZCW/off';
    } else if (move == 12) {
      button = 'ZCCW/off';
    }

    var xhr = new XMLHttpRequest();
    xhr.open('get', '' + button);
    xhr.send();
  }
</script>
{% endblock %}